#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Endpoint {
    DescribeInstance,
    Version,
    VmState,
    VmConfig,
    Actions,
    BootSource,
    CpuConfig,
    Entropy,
    Logger,
    MachineConfig,
    Metrics,
    Mmds,
    Drive,
    NetworkInterface,
    Serial,
    Snapshot,
    Vsock,
}
