[package]
name = "bangbang-snapshot-tools"
version.workspace = true
edition.workspace = true
repository.workspace = true
publish = false

[dependencies]
clap = { version = "=4.6.1", features = ["derive"] }

[target.'cfg(target_os = "macos")'.dependencies]
bangbang-runtime = { path = "../../crates/runtime" }
signal-hook = "0.3"

[dev-dependencies]
libc = "0.2"

[[bin]]
name = "rebase-snap"
path = "src/bin/rebase-snap.rs"

[[bin]]
name = "snapshot-editor"
path = "src/bin/snapshot-editor.rs"

[lints]
workspace = true
