[package]
name = "bangbang-hvf"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
bangbang-pager = { path = "../pager" }
bangbang-runtime = { path = "../runtime" }
crc64 = "2.0.0"
device_tree = "1.1.0"
libc = "0.2"
serde = "1.0.228"
serde_json = "1.0.140"
sha2 = "0.11.0"

[build-dependencies]
cc = "1"

[dev-dependencies]
plist = "1"

[[test]]
name = "guest_boot"
path = "tests/guest_boot.rs"
test = false

[[test]]
name = "hvf_lifecycle"
path = "tests/hvf_lifecycle.rs"
test = false

[lints]
workspace = true
