[package]
name = "bangbang"
version.workspace = true
edition.workspace = true
repository.workspace = true

[features]
default = []
elevated-bootstrap-probe = ["bangbang-session/elevated-bootstrap-probe"]
grant-integration-probe = ["dep:bangbang-pager", "bangbang-runtime/test-support"]
tracing = ["bangbang-runtime/tracing"]

[dependencies]
bangbang-api = { path = "../api" }
bangbang-hvf = { path = "../hvf" }
bangbang-pager = { path = "../pager", optional = true }
bangbang-runtime = { path = "../runtime" }
bangbang-session = { path = "../session" }
block2 = "0.6.2"
dispatch2 = "0.3.1"
libc = "0.2"
serde = "1"
serde_json = "1"
signal-hook = "0.3"
signal-hook-registry = "1"

[dev-dependencies]
bangbang-cpu-template-helper = { path = "../../tools/cpu-template-helper" }
bangbang-session = { path = "../session", features = ["test-support"] }
crc64 = "2.0.0"
plist = "1"
sha2 = "0.11.0"

[[test]]
name = "executable_hvf_e2e"
path = "tests/executable_hvf_e2e.rs"
test = false

[[test]]
name = "app_sandbox_process_e2e"
path = "tests/app_sandbox_process_e2e.rs"
test = false

[[test]]
name = "elevated_vmnet_e2e"
path = "tests/elevated_vmnet_e2e.rs"
test = false

[lints]
workspace = true
